export interface Problem {
  n: number;
  t: string;
  s: string;
  d: string;
  a: number;
}

export const PROBLEMS: Problem[] = [
  {"n":1,"t":"Two Sum","s":"two-sum","d":"Easy","a":47.1},
  {"n":2,"t":"Add Two Numbers","s":"add-two-numbers","d":"Medium","a":36.1},
  {"n":3,"t":"Longest Substring Without Repeating Characters","s":"longest-substring-without-repeating-characters","d":"Medium","a":31.8},
  {"n":4,"t":"Median of Two Sorted Arrays","s":"median-of-two-sorted-arrays","d":"Hard","a":31.9},
  {"n":5,"t":"Longest Palindromic Substring","s":"longest-palindromic-substring","d":"Medium","a":30.9},
  {"n":7,"t":"Reverse Integer","s":"reverse-integer","d":"Easy","a":26},
  {"n":8,"t":"String to Integer (atoi)","s":"string-to-integer-atoi","d":"Medium","a":15.8},
  {"n":9,"t":"Palindrome Number","s":"palindrome-number","d":"Easy","a":50.5},
  {"n":10,"t":"Regular Expression Matching","s":"regular-expression-matching","d":"Hard","a":27.6},
  {"n":11,"t":"Container With Most Water","s":"container-with-most-water","d":"Medium","a":53},
  {"n":12,"t":"Integer to Roman","s":"integer-to-roman","d":"Medium","a":57.5},
  {"n":13,"t":"Roman to Integer","s":"roman-to-integer","d":"Easy","a":57.3},
  {"n":14,"t":"Longest Common Prefix","s":"longest-common-prefix","d":"Easy","a":36.7},
  {"n":15,"t":"3Sum","s":"3sum","d":"Medium","a":28.6},
  {"n":16,"t":"3Sum Closest","s":"3sum-closest","d":"Medium","a":46.4},
  {"n":17,"t":"Letter Combinations of a Phone Number","s":"letter-combinations-of-a-phone-number","d":"Medium","a":50.4},
  {"n":18,"t":"4Sum","s":"4sum","d":"Medium","a":35.5},
  {"n":19,"t":"Remove Nth Node From End of List","s":"remove-nth-node-from-end-of-list","d":"Medium","a":36.3},
  {"n":20,"t":"Valid Parentheses","s":"valid-parentheses","d":"Easy","a":40.2},
  {"n":21,"t":"Merge Two Sorted Lists","s":"merge-two-sorted-lists","d":"Easy","a":56.9},
  {"n":22,"t":"Generate Parentheses","s":"generate-parentheses","d":"Medium","a":66.4},
  {"n":23,"t":"Merge k Sorted Lists","s":"merge-k-sorted-lists","d":"Hard","a":43.6},
  {"n":24,"t":"Swap Nodes in Pairs","s":"swap-nodes-in-pairs","d":"Medium","a":54.1},
  {"n":25,"t":"Reverse Nodes in k-Group","s":"reverse-nodes-in-k-group","d":"Hard","a":46.1},
  {"n":26,"t":"Remove Duplicates from Sorted Array","s":"remove-duplicates-from-sorted-array","d":"Easy","a":47.1},
  {"n":27,"t":"Remove Element","s":"remove-element","d":"Easy","a":49.8},
  {"n":28,"t":"Implement strStr()","s":"implement-strstr","d":"Easy","a":35.6},
  {"n":29,"t":"Divide Two Integers","s":"divide-two-integers","d":"Medium","a":17},
  {"n":30,"t":"Substring with Concatenation of All Words","s":"substring-with-concatenation-of-all-words","d":"Hard","a":26.6},
  {"n":31,"t":"Next Permutation","s":"next-permutation","d":"Medium","a":34.1},
  {"n":32,"t":"Longest Valid Parentheses","s":"longest-valid-parentheses","d":"Hard","a":30.1},
  {"n":33,"t":"Search in Rotated Sorted Array","s":"search-in-rotated-sorted-array","d":"Medium","a":36.4},
  {"n":34,"t":"Find First and Last Position of Element in Sorted Array","s":"find-first-and-last-position-of-element-in-sorted-array","d":"Medium","a":38.1},
  {"n":35,"t":"Search Insert Position","s":"search-insert-position","d":"Easy","a":42.9},
  {"n":36,"t":"Valid Sudoku","s":"valid-sudoku","d":"Medium","a":51.3},
  {"n":37,"t":"Sudoku Solver","s":"sudoku-solver","d":"Hard","a":48},
  {"n":38,"t":"Count and Say","s":"count-and-say","d":"Medium","a":46.7},
  {"n":39,"t":"Combination Sum","s":"combination-sum","d":"Medium","a":60.5},
  {"n":40,"t":"Combination Sum II","s":"combination-sum-ii","d":"Medium","a":50.8},
  {"n":41,"t":"First Missing Positive","s":"first-missing-positive","d":"Hard","a":34.4},
  {"n":42,"t":"Trapping Rain Water","s":"trapping-rain-water","d":"Hard","a":52.2},
  {"n":43,"t":"Multiply Strings","s":"multiply-strings","d":"Medium","a":35.4},
  {"n":44,"t":"Wildcard Matching","s":"wildcard-matching","d":"Hard","a":25.7},
  {"n":45,"t":"Jump Game II","s":"jump-game-ii","d":"Medium","a":32.9},
  {"n":46,"t":"Permutations","s":"permutations","d":"Medium","a":67.8},
  {"n":47,"t":"Permutations II","s":"permutations-ii","d":"Medium","a":50.4},
  {"n":48,"t":"Rotate Image","s":"rotate-image","d":"Medium","a":61.8},
  {"n":49,"t":"Group Anagrams","s":"group-anagrams","d":"Medium","a":60.4},
  {"n":50,"t":"Pow(x, n)","s":"powx-n","d":"Medium","a":31.3},
  {"n":51,"t":"N-Queens","s":"n-queens","d":"Hard","a":52.1},
  {"n":53,"t":"Maximum Subarray","s":"maximum-subarray","d":"Easy","a":48.1},
  {"n":54,"t":"Spiral Matrix","s":"spiral-matrix","d":"Medium","a":37.2},
  {"n":55,"t":"Jump Game","s":"jump-game","d":"Medium","a":35.5},
  {"n":56,"t":"Merge Intervals","s":"merge-intervals","d":"Medium","a":41.9},
  {"n":57,"t":"Insert Interval","s":"insert-interval","d":"Medium","a":35.7},
  {"n":61,"t":"Rotate List","s":"rotate-list","d":"Medium","a":32.2},
  {"n":62,"t":"Unique Paths","s":"unique-paths","d":"Medium","a":56.8},
  {"n":63,"t":"Unique Paths II","s":"unique-paths-ii","d":"Medium","a":36},
  {"n":64,"t":"Minimum Path Sum","s":"minimum-path-sum","d":"Medium","a":56.9},
  {"n":66,"t":"Plus One","s":"plus-one","d":"Easy","a":42.2},
  {"n":67,"t":"Add Binary","s":"add-binary","d":"Easy","a":47.8},
  {"n":68,"t":"Text Justification","s":"text-justification","d":"Hard","a":31},
  {"n":69,"t":"Sqrt(x)","s":"sqrtx","d":"Easy","a":35.7},
  {"n":70,"t":"Climbing Stairs","s":"climbing-stairs","d":"Easy","a":49},
  {"n":71,"t":"Simplify Path","s":"simplify-path","d":"Medium","a":35.3},
  {"n":72,"t":"Edit Distance","s":"edit-distance","d":"Hard","a":47.7},
  {"n":73,"t":"Set Matrix Zeroes","s":"set-matrix-zeroes","d":"Medium","a":45},
  {"n":74,"t":"Search a 2D Matrix","s":"search-a-2d-matrix","d":"Medium","a":38.7},
  {"n":75,"t":"Sort Colors","s":"sort-colors","d":"Medium","a":50.5},
  {"n":76,"t":"Minimum Window Substring","s":"minimum-window-substring","d":"Hard","a":36.5},
  {"n":77,"t":"Combinations","s":"combinations","d":"Medium","a":58.7},
  {"n":78,"t":"Subsets","s":"subsets","d":"Medium","a":66.4},
  {"n":79,"t":"Word Search","s":"word-search","d":"Medium","a":37.6},
  {"n":81,"t":"Search in Rotated Sorted Array II","s":"search-in-rotated-sorted-array-ii","d":"Medium","a":33.8},
  {"n":82,"t":"Remove Duplicates from Sorted List II","s":"remove-duplicates-from-sorted-list-ii","d":"Medium","a":39.9},
  {"n":84,"t":"Largest Rectangle in Histogram","s":"largest-rectangle-in-histogram","d":"Hard","a":37.9},
  {"n":85,"t":"Maximal Rectangle","s":"maximal-rectangle","d":"Hard","a":40.1},
  {"n":86,"t":"Partition List","s":"partition-list","d":"Medium","a":45.2},
  {"n":88,"t":"Merge Sorted Array","s":"merge-sorted-array","d":"Easy","a":41.1},
  {"n":91,"t":"Decode Ways","s":"decode-ways","d":"Medium","a":27.4},
  {"n":92,"t":"Reverse Linked List II","s":"reverse-linked-list-ii","d":"Medium","a":41.1},
  {"n":93,"t":"Restore IP Addresses","s":"restore-ip-addresses","d":"Medium","a":38.4},
  {"n":94,"t":"Binary Tree Inorder Traversal","s":"binary-tree-inorder-traversal","d":"Easy","a":67},
  {"n":96,"t":"Unique Binary Search Trees","s":"unique-binary-search-trees","d":"Medium","a":55.1},
  {"n":98,"t":"Validate Binary Search Tree","s":"validate-binary-search-tree","d":"Medium","a":29.2},
  {"n":99,"t":"Recover Binary Search Tree","s":"recover-binary-search-tree","d":"Medium","a":43.3},
  {"n":100,"t":"Same Tree","s":"same-tree","d":"Easy","a":54.4},
  {"n":101,"t":"Symmetric Tree","s":"symmetric-tree","d":"Easy","a":49},
  {"n":102,"t":"Binary Tree Level Order Traversal","s":"binary-tree-level-order-traversal","d":"Medium","a":57.8},
  {"n":103,"t":"Binary Tree Zigzag Level Order Traversal","s":"binary-tree-zigzag-level-order-traversal","d":"Medium","a":50.9},
  {"n":104,"t":"Maximum Depth of Binary Tree","s":"maximum-depth-of-binary-tree","d":"Easy","a":68.9},
  {"n":105,"t":"Construct Binary Tree from Preorder and Inorder Traversal","s":"construct-binary-tree-from-preorder-and-inorder-traversal","d":"Medium","a":53.7},
  {"n":109,"t":"Convert Sorted List to Binary Search Tree","s":"convert-sorted-list-to-binary-search-tree","d":"Medium","a":52.3},
  {"n":110,"t":"Balanced Binary Tree","s":"balanced-binary-tree","d":"Easy","a":45.1},
  {"n":111,"t":"Minimum Depth of Binary Tree","s":"minimum-depth-of-binary-tree","d":"Easy","a":40.3},
  {"n":112,"t":"Path Sum","s":"path-sum","d":"Easy","a":43},
  {"n":114,"t":"Flatten Binary Tree to Linked List","s":"flatten-binary-tree-to-linked-list","d":"Medium","a":53.7},
  {"n":116,"t":"Populating Next Right Pointers in Each Node","s":"populating-next-right-pointers-in-each-node","d":"Medium","a":50.5},
  {"n":117,"t":"Populating Next Right Pointers in Each Node II","s":"populating-next-right-pointers-in-each-node-ii","d":"Medium","a":42.9},
  {"n":120,"t":"Triangle","s":"triangle","d":"Medium","a":47.3},
  {"n":121,"t":"Best Time to Buy and Sell Stock","s":"best-time-to-buy-and-sell-stock","d":"Easy","a":52.1},
  {"n":122,"t":"Best Time to Buy and Sell Stock II","s":"best-time-to-buy-and-sell-stock-ii","d":"Easy","a":59.2},
  {"n":123,"t":"Best Time to Buy and Sell Stock III","s":"best-time-to-buy-and-sell-stock-iii","d":"Hard","a":40.6},
  {"n":124,"t":"Binary Tree Maximum Path Sum","s":"binary-tree-maximum-path-sum","d":"Hard","a":36},
  {"n":125,"t":"Valid Palindrome","s":"valid-palindrome","d":"Easy","a":39},
  {"n":126,"t":"Word Ladder II","s":"word-ladder-ii","d":"Hard","a":24.2},
  {"n":127,"t":"Word Ladder","s":"word-ladder","d":"Hard","a":32.6},
  {"n":128,"t":"Longest Consecutive Sequence","s":"longest-consecutive-sequence","d":"Medium","a":47.2},
  {"n":130,"t":"Surrounded Regions","s":"surrounded-regions","d":"Medium","a":30.3},
  {"n":133,"t":"Clone Graph","s":"clone-graph","d":"Medium","a":40.8},
  {"n":134,"t":"Gas Station","s":"gas-station","d":"Medium","a":42},
  {"n":135,"t":"Candy","s":"candy","d":"Hard","a":33.8},
  {"n":136,"t":"Single Number","s":"single-number","d":"Easy","a":67},
  {"n":137,"t":"Single Number II","s":"single-number-ii","d":"Medium","a":54.5},
  {"n":138,"t":"Copy List with Random Pointer","s":"copy-list-with-random-pointer","d":"Medium","a":42.4},
  {"n":139,"t":"Word Break","s":"word-break","d":"Medium","a":42.3},
  {"n":140,"t":"Word Break II","s":"word-break-ii","d":"Hard","a":36.4},
  {"n":141,"t":"Linked List Cycle","s":"linked-list-cycle","d":"Easy","a":43.4},
  {"n":142,"t":"Linked List Cycle II","s":"linked-list-cycle-ii","d":"Medium","a":40.5},
  {"n":143,"t":"Reorder List","s":"reorder-list","d":"Medium","a":41.8},
  {"n":144,"t":"Binary Tree Preorder Traversal","s":"binary-tree-preorder-traversal","d":"Easy","a":58.4},
  {"n":145,"t":"Binary Tree Postorder Traversal","s":"binary-tree-postorder-traversal","d":"Easy","a":58.8},
  {"n":146,"t":"LRU Cache","s":"lru-cache","d":"Medium","a":36.9},
  {"n":149,"t":"Max Points on a Line","s":"max-points-on-a-line","d":"Hard","a":18.2},
  {"n":150,"t":"Evaluate Reverse Polish Notation","s":"evaluate-reverse-polish-notation","d":"Medium","a":39.5},
  {"n":152,"t":"Maximum Product Subarray","s":"maximum-product-subarray","d":"Medium","a":33.1},
  {"n":153,"t":"Find Minimum in Rotated Sorted Array","s":"find-minimum-in-rotated-sorted-array","d":"Medium","a":46.6},
  {"n":154,"t":"Find Minimum in Rotated Sorted Array II","s":"find-minimum-in-rotated-sorted-array-ii","d":"Hard","a":42.2},
  {"n":155,"t":"Min Stack","s":"min-stack","d":"Easy","a":47.3},
  {"n":159,"t":"Longest Substring with At Most Two Distinct Characters","s":"longest-substring-with-at-most-two-distinct-characters","d":"Medium","a":51},
  {"n":160,"t":"Intersection of Two Linked Lists","s":"intersection-of-two-linked-lists","d":"Easy","a":45.4},
  {"n":162,"t":"Find Peak Element","s":"find-peak-element","d":"Medium","a":44.2},
  {"n":165,"t":"Compare Version Numbers","s":"compare-version-numbers","d":"Medium","a":31},
  {"n":167,"t":"Two Sum II - Input array is sorted","s":"two-sum-ii-input-array-is-sorted","d":"Easy","a":56.1},
  {"n":169,"t":"Majority Element","s":"majority-element","d":"Easy","a":60.6},
  {"n":173,"t":"Binary Search Tree Iterator","s":"binary-search-tree-iterator","d":"Medium","a":61.4},
  {"n":174,"t":"Dungeon Game","s":"dungeon-game","d":"Hard","a":33.7},
  {"n":175,"t":"Combine Two Tables","s":"combine-two-tables","d":"Easy","a":65.6},
  {"n":176,"t":"Second Highest Salary","s":"second-highest-salary","d":"Easy","a":33.9},
  {"n":179,"t":"Largest Number","s":"largest-number","d":"Medium","a":31.1},
  {"n":180,"t":"Consecutive Numbers","s":"consecutive-numbers","d":"Medium","a":43.2},
  {"n":181,"t":"Employees Earning More Than Their Managers","s":"employees-earning-more-than-their-managers","d":"Easy","a":62},
  {"n":184,"t":"Department Highest Salary","s":"department-highest-salary","d":"Medium","a":41.7},
  {"n":185,"t":"Department Top Three Salaries","s":"department-top-three-salaries","d":"Hard","a":41},
  {"n":188,"t":"Best Time to Buy and Sell Stock IV","s":"best-time-to-buy-and-sell-stock-iv","d":"Hard","a":30.6},
  {"n":189,"t":"Rotate Array","s":"rotate-array","d":"Medium","a":36.9},
  {"n":196,"t":"Delete Duplicate Emails","s":"delete-duplicate-emails","d":"Easy","a":46.9},
  {"n":198,"t":"House Robber","s":"house-robber","d":"Medium","a":43.5},
  {"n":199,"t":"Binary Tree Right Side View","s":"binary-tree-right-side-view","d":"Medium","a":57},
  {"n":200,"t":"Number of Islands","s":"number-of-islands","d":"Medium","a":50.2},
  {"n":201,"t":"Bitwise AND of Numbers Range","s":"bitwise-and-of-numbers-range","d":"Medium","a":39.8},
  {"n":202,"t":"Happy Number","s":"happy-number","d":"Easy","a":51.6},
  {"n":203,"t":"Remove Linked List Elements","s":"remove-linked-list-elements","d":"Easy","a":39.9},
  {"n":204,"t":"Count Primes","s":"count-primes","d":"Easy","a":32.8},
  {"n":205,"t":"Isomorphic Strings","s":"isomorphic-strings","d":"Easy","a":40.8},
  {"n":206,"t":"Reverse Linked List","s":"reverse-linked-list","d":"Easy","a":66.4},
  {"n":207,"t":"Course Schedule","s":"course-schedule","d":"Medium","a":44.4},
  {"n":208,"t":"Implement Trie (Prefix Tree)","s":"implement-trie-prefix-tree","d":"Medium","a":53.4},
  {"n":209,"t":"Minimum Size Subarray Sum","s":"minimum-size-subarray-sum","d":"Medium","a":40.3},
  {"n":210,"t":"Course Schedule II","s":"course-schedule-ii","d":"Medium","a":43.5},
  {"n":211,"t":"Design Add and Search Words Data Structure","s":"design-add-and-search-words-data-structure","d":"Medium","a":41.2},
  {"n":212,"t":"Word Search II","s":"word-search-ii","d":"Hard","a":37.7},
  {"n":215,"t":"Kth Largest Element in an Array","s":"kth-largest-element-in-an-array","d":"Medium","a":59.6},
  {"n":217,"t":"Contains Duplicate","s":"contains-duplicate","d":"Easy","a":57.4},
  {"n":218,"t":"The Skyline Problem","s":"the-skyline-problem","d":"Hard","a":37},
  {"n":219,"t":"Contains Duplicate II","s":"contains-duplicate-ii","d":"Easy","a":39.2},
  {"n":221,"t":"Maximal Square","s":"maximal-square","d":"Medium","a":40.1},
  {"n":222,"t":"Count Complete Tree Nodes","s":"count-complete-tree-nodes","d":"Medium","a":50.4},
  {"n":224,"t":"Basic Calculator","s":"basic-calculator","d":"Hard","a":38.5},
  {"n":225,"t":"Implement Stack using Queues","s":"implement-stack-using-queues","d":"Easy","a":48.5},
  {"n":226,"t":"Invert Binary Tree","s":"invert-binary-tree","d":"Easy","a":67.9},
  {"n":227,"t":"Basic Calculator II","s":"basic-calculator-ii","d":"Medium","a":39.1},
  {"n":229,"t":"Majority Element II","s":"majority-element-ii","d":"Medium","a":39.5},
  {"n":230,"t":"Kth Smallest Element in a BST","s":"kth-smallest-element-in-a-bst","d":"Medium","a":63.6},
  {"n":232,"t":"Implement Queue using Stacks","s":"implement-queue-using-stacks","d":"Easy","a":53.3},
  {"n":234,"t":"Palindrome Linked List","s":"palindrome-linked-list","d":"Easy","a":42.8},
  {"n":235,"t":"Lowest Common Ancestor of a Binary Search Tree","s":"lowest-common-ancestor-of-a-binary-search-tree","d":"Easy","a":52.7},
  {"n":236,"t":"Lowest Common Ancestor of a Binary Tree","s":"lowest-common-ancestor-of-a-binary-tree","d":"Medium","a":50.2},
  {"n":238,"t":"Product of Array Except Self","s":"product-of-array-except-self","d":"Medium","a":61.6},
  {"n":239,"t":"Sliding Window Maximum","s":"sliding-window-maximum","d":"Hard","a":45},
  {"n":240,"t":"Search a 2D Matrix II","s":"search-a-2d-matrix-ii","d":"Medium","a":45.8},
  {"n":242,"t":"Valid Anagram","s":"valid-anagram","d":"Easy","a":59.3},
  {"n":244,"t":"Shortest Word Distance II","s":"shortest-word-distance-ii","d":"Medium","a":55.4},
  {"n":252,"t":"Meeting Rooms","s":"meeting-rooms","d":"Easy","a":55.7},
  {"n":253,"t":"Meeting Rooms II","s":"meeting-rooms-ii","d":"Medium","a":47.5},
  {"n":258,"t":"Add Digits","s":"add-digits","d":"Easy","a":59},
  {"n":261,"t":"Graph Valid Tree","s":"graph-valid-tree","d":"Medium","a":43.7},
  {"n":262,"t":"Trips and Users","s":"trips-and-users","d":"Hard","a":36.2},
  {"n":268,"t":"Missing Number","s":"missing-number","d":"Easy","a":56},
  {"n":269,"t":"Alien Dictionary","s":"alien-dictionary","d":"Hard","a":33.9},
  {"n":273,"t":"Integer to English Words","s":"integer-to-english-words","d":"Hard","a":28.6},
  {"n":277,"t":"Find the Celebrity","s":"find-the-celebrity","d":"Medium","a":44.5},
  {"n":278,"t":"First Bad Version","s":"first-bad-version","d":"Easy","a":38.3},
  {"n":279,"t":"Perfect Squares","s":"perfect-squares","d":"Medium","a":49.6},
  {"n":283,"t":"Move Zeroes","s":"move-zeroes","d":"Easy","a":58.9},
  {"n":284,"t":"Peeking Iterator","s":"peeking-iterator","d":"Medium","a":51.3},
  {"n":285,"t":"Inorder Successor in BST","s":"inorder-successor-in-bst","d":"Medium","a":44.2},
  {"n":286,"t":"Walls and Gates","s":"walls-and-gates","d":"Medium","a":57.2},
  {"n":287,"t":"Find the Duplicate Number","s":"find-the-duplicate-number","d":"Medium","a":58.2},
  {"n":289,"t":"Game of Life","s":"game-of-life","d":"Medium","a":59.6},
  {"n":295,"t":"Find Median from Data Stream","s":"find-median-from-data-stream","d":"Hard","a":48.1},
  {"n":296,"t":"Best Meeting Point","s":"best-meeting-point","d":"Hard","a":58.4},
  {"n":297,"t":"Serialize and Deserialize Binary Tree","s":"serialize-and-deserialize-binary-tree","d":"Hard","a":50.9},
  {"n":300,"t":"Longest Increasing Subsequence","s":"longest-increasing-subsequence","d":"Medium","a":45.2},
  {"n":301,"t":"Remove Invalid Parentheses","s":"remove-invalid-parentheses","d":"Hard","a":45.2},
  {"n":305,"t":"Number of Islands II","s":"number-of-islands-ii","d":"Hard","a":39.5},
  {"n":312,"t":"Burst Balloons","s":"burst-balloons","d":"Hard","a":54.1},
  {"n":314,"t":"Binary Tree Vertical Order Traversal","s":"binary-tree-vertical-order-traversal","d":"Medium","a":47.7},
  {"n":315,"t":"Count of Smaller Numbers After Self","s":"count-of-smaller-numbers-after-self","d":"Hard","a":42.3},
  {"n":316,"t":"Remove Duplicate Letters","s":"remove-duplicate-letters","d":"Medium","a":39.7},
  {"n":322,"t":"Coin Change","s":"coin-change","d":"Medium","a":38.1},
  {"n":323,"t":"Number of Connected Components in an Undirected Graph","s":"number-of-connected-components-in-an-undirected-graph","d":"Medium","a":58.7},
  {"n":324,"t":"Wiggle Sort II","s":"wiggle-sort-ii","d":"Medium","a":31},
  {"n":328,"t":"Odd Even Linked List","s":"odd-even-linked-list","d":"Medium","a":57.6},
  {"n":329,"t":"Longest Increasing Path in a Matrix","s":"longest-increasing-path-in-a-matrix","d":"Hard","a":46.9},
  {"n":332,"t":"Reconstruct Itinerary","s":"reconstruct-itinerary","d":"Medium","a":38.5},
  {"n":334,"t":"Increasing Triplet Subsequence","s":"increasing-triplet-subsequence","d":"Medium","a":41},
  {"n":337,"t":"House Robber III","s":"house-robber-iii","d":"Medium","a":52.1},
  {"n":338,"t":"Counting Bits","s":"counting-bits","d":"Easy","a":71},
  {"n":339,"t":"Nested List Weight Sum","s":"nested-list-weight-sum","d":"Medium","a":77.3},
  {"n":341,"t":"Flatten Nested List Iterator","s":"flatten-nested-list-iterator","d":"Medium","a":56.3},
  {"n":344,"t":"Reverse String","s":"reverse-string","d":"Easy","a":71.2},
  {"n":345,"t":"Reverse Vowels of a String","s":"reverse-vowels-of-a-string","d":"Easy","a":45.5},
  {"n":346,"t":"Moving Average from Data Stream","s":"moving-average-from-data-stream","d":"Easy","a":74.1},
  {"n":347,"t":"Top K Frequent Elements","s":"top-k-frequent-elements","d":"Medium","a":62.9},
  {"n":348,"t":"Design Tic-Tac-Toe","s":"design-tic-tac-toe","d":"Medium","a":56.2},
  {"n":349,"t":"Intersection of Two Arrays","s":"intersection-of-two-arrays","d":"Easy","a":66},
  {"n":350,"t":"Intersection of Two Arrays II","s":"intersection-of-two-arrays-ii","d":"Easy","a":52.5},
  {"n":353,"t":"Design Snake Game","s":"design-snake-game","d":"Medium","a":36.6},
  {"n":354,"t":"Russian Doll Envelopes","s":"russian-doll-envelopes","d":"Hard","a":38.2},
  {"n":355,"t":"Design Twitter","s":"design-twitter","d":"Medium","a":32.2},
  {"n":362,"t":"Design Hit Counter","s":"design-hit-counter","d":"Medium","a":65.9},
  {"n":366,"t":"Find Leaves of Binary Tree","s":"find-leaves-of-binary-tree","d":"Medium","a":72.7},
  {"n":368,"t":"Largest Divisible Subset","s":"largest-divisible-subset","d":"Medium","a":38.6},
  {"n":373,"t":"Find K Pairs with Smallest Sums","s":"find-k-pairs-with-smallest-sums","d":"Medium","a":38.5},
  {"n":377,"t":"Combination Sum IV","s":"combination-sum-iv","d":"Medium","a":47.3},
  {"n":378,"t":"Kth Smallest Element in a Sorted Matrix","s":"kth-smallest-element-in-a-sorted-matrix","d":"Medium","a":57},
  {"n":380,"t":"Insert Delete GetRandom O(1)","s":"insert-delete-getrandom-o1","d":"Medium","a":49.4},
  {"n":381,"t":"Insert Delete GetRandom O(1) - Duplicates allowed","s":"insert-delete-getrandom-o1-duplicates-allowed","d":"Hard","a":35.1},
  {"n":383,"t":"Ransom Note","s":"ransom-note","d":"Easy","a":53.6},
  {"n":387,"t":"First Unique Character in a String","s":"first-unique-character-in-a-string","d":"Easy","a":54.4},
  {"n":388,"t":"Longest Absolute File Path","s":"longest-absolute-file-path","d":"Medium","a":43.6},
  {"n":394,"t":"Decode String","s":"decode-string","d":"Medium","a":53.5},
  {"n":395,"t":"Longest Substring with At Least K Repeating Characters","s":"longest-substring-with-at-least-k-repeating-characters","d":"Medium","a":43.8},
  {"n":399,"t":"Evaluate Division","s":"evaluate-division","d":"Medium","a":55},
  {"n":400,"t":"Nth Digit","s":"nth-digit","d":"Medium","a":32.6},
  {"n":402,"t":"Remove K Digits","s":"remove-k-digits","d":"Medium","a":28.7},
  {"n":403,"t":"Frog Jump","s":"frog-jump","d":"Hard","a":41.9},
  {"n":407,"t":"Trapping Rain Water II","s":"trapping-rain-water-ii","d":"Hard","a":44.9},
  {"n":410,"t":"Split Array Largest Sum","s":"split-array-largest-sum","d":"Hard","a":47.1},
  {"n":412,"t":"Fizz Buzz","s":"fizz-buzz","d":"Easy","a":64.2},
  {"n":415,"t":"Add Strings","s":"add-strings","d":"Easy","a":49.1},
  {"n":416,"t":"Partition Equal Subset Sum","s":"partition-equal-subset-sum","d":"Medium","a":45.2},
  {"n":417,"t":"Pacific Atlantic Water Flow","s":"pacific-atlantic-water-flow","d":"Medium","a":44.7},
  {"n":424,"t":"Longest Repeating Character Replacement","s":"longest-repeating-character-replacement","d":"Medium","a":48.8},
  {"n":426,"t":"Convert Binary Search Tree to Sorted Doubly Linked List","s":"convert-binary-search-tree-to-sorted-doubly-linked-list","d":"Medium","a":62},
  {"n":428,"t":"Serialize and Deserialize N-ary Tree","s":"serialize-and-deserialize-n-ary-tree","d":"Hard","a":62.3},
  {"n":429,"t":"N-ary Tree Level Order Traversal","s":"n-ary-tree-level-order-traversal","d":"Medium","a":67.2},
  {"n":432,"t":"All O`one Data Structure","s":"all-oone-data-structure","d":"Hard","a":33.6},
  {"n":435,"t":"Non-overlapping Intervals","s":"non-overlapping-intervals","d":"Medium","a":44.5},
  {"n":437,"t":"Path Sum III","s":"path-sum-iii","d":"Medium","a":48.6},
  {"n":438,"t":"Find All Anagrams in a String","s":"find-all-anagrams-in-a-string","d":"Medium","a":45.5},
  {"n":442,"t":"Find All Duplicates in an Array","s":"find-all-duplicates-in-an-array","d":"Medium","a":69.6},
  {"n":443,"t":"String Compression","s":"string-compression","d":"Medium","a":44.8},
  {"n":445,"t":"Add Two Numbers II","s":"add-two-numbers-ii","d":"Medium","a":56.9},
  {"n":448,"t":"Find All Numbers Disappeared in an Array","s":"find-all-numbers-disappeared-in-an-array","d":"Easy","a":56.5},
  {"n":449,"t":"Serialize and Deserialize BST","s":"serialize-and-deserialize-bst","d":"Medium","a":54.7},
  {"n":454,"t":"4Sum II","s":"4sum-ii","d":"Medium","a":54.9},
  {"n":456,"t":"132 Pattern","s":"132-pattern","d":"Medium","a":30.7},
  {"n":460,"t":"LFU Cache","s":"lfu-cache","d":"Hard","a":37.1},
  {"n":471,"t":"Encode String with Shortest Length","s":"encode-string-with-shortest-length","d":"Hard","a":50},
  {"n":472,"t":"Concatenated Words","s":"concatenated-words","d":"Hard","a":43.9},
  {"n":489,"t":"Robot Room Cleaner","s":"robot-room-cleaner","d":"Hard","a":73.4},
  {"n":490,"t":"The Maze","s":"the-maze","d":"Medium","a":53.3},
  {"n":493,"t":"Reverse Pairs","s":"reverse-pairs","d":"Hard","a":27.6},
  {"n":494,"t":"Target Sum","s":"target-sum","d":"Medium","a":45.6},
  {"n":496,"t":"Next Greater Element I","s":"next-greater-element-i","d":"Easy","a":66.3},
  {"n":498,"t":"Diagonal Traverse","s":"diagonal-traverse","d":"Medium","a":51.2},
  {"n":503,"t":"Next Greater Element II","s":"next-greater-element-ii","d":"Medium","a":59.2},
  {"n":509,"t":"Fibonacci Number","s":"fibonacci-number","d":"Easy","a":67.8},
  {"n":516,"t":"Longest Palindromic Subsequence","s":"longest-palindromic-subsequence","d":"Medium","a":56.4},
  {"n":518,"t":"Coin Change 2","s":"coin-change-2","d":"Medium","a":52.8},
  {"n":523,"t":"Continuous Subarray Sum","s":"continuous-subarray-sum","d":"Medium","a":25.2},
  {"n":525,"t":"Contiguous Array","s":"contiguous-array","d":"Medium","a":43.9},
  {"n":528,"t":"Random Pick with Weight","s":"random-pick-with-weight","d":"Medium","a":45},
  {"n":535,"t":"Encode and Decode TinyURL","s":"encode-and-decode-tinyurl","d":"Medium","a":82.6},
  {"n":540,"t":"Single Element in a Sorted Array","s":"single-element-in-a-sorted-array","d":"Medium","a":58},
  {"n":542,"t":"01 Matrix","s":"01-matrix","d":"Medium","a":41.5},
  {"n":543,"t":"Diameter of Binary Tree","s":"diameter-of-binary-tree","d":"Easy","a":50.2},
  {"n":545,"t":"Boundary of Binary Tree","s":"boundary-of-binary-tree","d":"Medium","a":41},
  {"n":547,"t":"Number of Provinces","s":"number-of-provinces","d":"Medium","a":61.2},
  {"n":557,"t":"Reverse Words in a String III","s":"reverse-words-in-a-string-iii","d":"Easy","a":72.9},
  {"n":560,"t":"Subarray Sum Equals K","s":"subarray-sum-equals-k","d":"Medium","a":43.7},
  {"n":564,"t":"Find the Closest Palindrome","s":"find-the-closest-palindrome","d":"Hard","a":20.4},
  {"n":567,"t":"Permutation in String","s":"permutation-in-string","d":"Medium","a":44.6},
  {"n":572,"t":"Subtree of Another Tree","s":"subtree-of-another-tree","d":"Easy","a":44.6},
  {"n":576,"t":"Out of Boundary Paths","s":"out-of-boundary-paths","d":"Medium","a":36.4},
  {"n":579,"t":"Find Cumulative Salary of an Employee","s":"find-cumulative-salary-of-an-employee","d":"Hard","a":38.8},
  {"n":581,"t":"Shortest Unsorted Continuous Subarray","s":"shortest-unsorted-continuous-subarray","d":"Medium","a":33.1},
  {"n":588,"t":"Design In-Memory File System","s":"design-in-memory-file-system","d":"Hard","a":46.9},
  {"n":590,"t":"N-ary Tree Postorder Traversal","s":"n-ary-tree-postorder-traversal","d":"Easy","a":74.2},
  {"n":609,"t":"Find Duplicate File in System","s":"find-duplicate-file-in-system","d":"Medium","a":63},
  {"n":615,"t":"Average Salary: Departments VS Company","s":"average-salary-departments-vs-company","d":"Hard","a":53.8},
  {"n":617,"t":"Merge Two Binary Trees","s":"merge-two-binary-trees","d":"Easy","a":75.8},
  {"n":621,"t":"Task Scheduler","s":"task-scheduler","d":"Medium","a":52.6},
  {"n":622,"t":"Design Circular Queue","s":"design-circular-queue","d":"Medium","a":47.8},
  {"n":626,"t":"Exchange Seats","s":"exchange-seats","d":"Medium","a":66.9},
  {"n":628,"t":"Maximum Product of Three Numbers","s":"maximum-product-of-three-numbers","d":"Easy","a":46.7},
  {"n":632,"t":"Smallest Range Covering Elements from K Lists","s":"smallest-range-covering-elements-from-k-lists","d":"Hard","a":55.1},
  {"n":635,"t":"Design Log Storage System","s":"design-log-storage-system","d":"Medium","a":60.5},
  {"n":636,"t":"Exclusive Time of Functions","s":"exclusive-time-of-functions","d":"Medium","a":55.8},
  {"n":641,"t":"Design Circular Deque","s":"design-circular-deque","d":"Medium","a":56.4},
  {"n":642,"t":"Design Search Autocomplete System","s":"design-search-autocomplete-system","d":"Hard","a":46.9},
  {"n":646,"t":"Maximum Length of Pair Chain","s":"maximum-length-of-pair-chain","d":"Medium","a":53.6},
  {"n":647,"t":"Palindromic Substrings","s":"palindromic-substrings","d":"Medium","a":62.9},
  {"n":650,"t":"2 Keys Keyboard","s":"2-keys-keyboard","d":"Medium","a":50.6},
  {"n":652,"t":"Find Duplicate Subtrees","s":"find-duplicate-subtrees","d":"Medium","a":53.6},
  {"n":657,"t":"Robot Return to Origin","s":"robot-return-to-origin","d":"Easy","a":74.3},
  {"n":658,"t":"Find K Closest Elements","s":"find-k-closest-elements","d":"Medium","a":42.7},
  {"n":674,"t":"Longest Continuous Increasing Subsequence","s":"longest-continuous-increasing-subsequence","d":"Easy","a":46.3},
  {"n":675,"t":"Cut Off Trees for Golf Event","s":"cut-off-trees-for-golf-event","d":"Hard","a":35.5},
  {"n":678,"t":"Valid Parenthesis String","s":"valid-parenthesis-string","d":"Medium","a":31.9},
  {"n":682,"t":"Baseball Game","s":"baseball-game","d":"Easy","a":67.8},
  {"n":684,"t":"Redundant Connection","s":"redundant-connection","d":"Medium","a":59.5},
  {"n":685,"t":"Redundant Connection II","s":"redundant-connection-ii","d":"Hard","a":33.2},
  {"n":688,"t":"Knight Probability in Chessboard","s":"knight-probability-in-chessboard","d":"Medium","a":50.6},
  {"n":692,"t":"Top K Frequent Words","s":"top-k-frequent-words","d":"Medium","a":53.5},
  {"n":694,"t":"Number of Distinct Islands","s":"number-of-distinct-islands","d":"Medium","a":58.5},
  {"n":695,"t":"Max Area of Island","s":"max-area-of-island","d":"Medium","a":66.7},
  {"n":703,"t":"Kth Largest Element in a Stream","s":"kth-largest-element-in-a-stream","d":"Easy","a":51.3},
  {"n":706,"t":"Design HashMap","s":"design-hashmap","d":"Easy","a":64},
  {"n":709,"t":"To Lower Case","s":"to-lower-case","d":"Easy","a":80.6},
  {"n":713,"t":"Subarray Product Less Than K","s":"subarray-product-less-than-k","d":"Medium","a":40.7},
  {"n":715,"t":"Range Module","s":"range-module","d":"Hard","a":41.5},
  {"n":716,"t":"Max Stack","s":"max-stack","d":"Easy","a":43.5},
  {"n":718,"t":"Maximum Length of Repeated Subarray","s":"maximum-length-of-repeated-subarray","d":"Medium","a":50.8},
  {"n":721,"t":"Accounts Merge","s":"accounts-merge","d":"Medium","a":52.9},
  {"n":726,"t":"Number of Atoms","s":"number-of-atoms","d":"Hard","a":51.1},
  {"n":727,"t":"Minimum Window Subsequence","s":"minimum-window-subsequence","d":"Hard","a":42.7},
  {"n":733,"t":"Flood Fill","s":"flood-fill","d":"Easy","a":56.1},
  {"n":735,"t":"Asteroid Collision","s":"asteroid-collision","d":"Medium","a":43.5},
  {"n":739,"t":"Daily Temperatures","s":"daily-temperatures","d":"Medium","a":65.2},
  {"n":743,"t":"Network Delay Time","s":"network-delay-time","d":"Medium","a":46},
  {"n":746,"t":"Min Cost Climbing Stairs","s":"min-cost-climbing-stairs","d":"Easy","a":53.3},
  {"n":752,"t":"Open the Lock","s":"open-the-lock","d":"Medium","a":54.7},
  {"n":759,"t":"Employee Free Time","s":"employee-free-time","d":"Hard","a":69},
  {"n":763,"t":"Partition Labels","s":"partition-labels","d":"Medium","a":78.2},
  {"n":767,"t":"Reorganize String","s":"reorganize-string","d":"Medium","a":50.6},
  {"n":771,"t":"Jewels and Stones","s":"jewels-and-stones","d":"Easy","a":87.1},
  {"n":772,"t":"Basic Calculator III","s":"basic-calculator-iii","d":"Hard","a":44.8},
  {"n":775,"t":"Global and Local Inversions","s":"global-and-local-inversions","d":"Medium","a":46.1},
  {"n":783,"t":"Minimum Distance Between BST Nodes","s":"minimum-distance-between-bst-nodes","d":"Easy","a":54.5},
  {"n":785,"t":"Is Graph Bipartite?","s":"is-graph-bipartite","d":"Medium","a":49},
  {"n":787,"t":"Cheapest Flights Within K Stops","s":"cheapest-flights-within-k-stops","d":"Medium","a":38.9},
  {"n":790,"t":"Domino and Tromino Tiling","s":"domino-and-tromino-tiling","d":"Medium","a":40.6},
  {"n":792,"t":"Number of Matching Subsequences","s":"number-of-matching-subsequences","d":"Medium","a":48.6},
  {"n":794,"t":"Valid Tic-Tac-Toe State","s":"valid-tic-tac-toe-state","d":"Medium","a":34.3},
  {"n":796,"t":"Rotate String","s":"rotate-string","d":"Easy","a":49},
  {"n":797,"t":"All Paths From Source to Target","s":"all-paths-from-source-to-target","d":"Medium","a":78.8},
  {"n":814,"t":"Binary Tree Pruning","s":"binary-tree-pruning","d":"Medium","a":71.7},
  {"n":815,"t":"Bus Routes","s":"bus-routes","d":"Hard","a":43.8},
  {"n":819,"t":"Most Common Word","s":"most-common-word","d":"Easy","a":45.4},
  {"n":826,"t":"Most Profit Assigning Work","s":"most-profit-assigning-work","d":"Medium","a":39.5},
  {"n":829,"t":"Consecutive Numbers Sum","s":"consecutive-numbers-sum","d":"Hard","a":39.3},
  {"n":836,"t":"Rectangle Overlap","s":"rectangle-overlap","d":"Easy","a":42.8},
  {"n":841,"t":"Keys and Rooms","s":"keys-and-rooms","d":"Medium","a":66.8},
  {"n":844,"t":"Backspace String Compare","s":"backspace-string-compare","d":"Easy","a":47.2},
  {"n":849,"t":"Maximize Distance to Closest Person","s":"maximize-distance-to-closest-person","d":"Medium","a":44.7},
  {"n":853,"t":"Car Fleet","s":"car-fleet","d":"Medium","a":44.8},
  {"n":856,"t":"Score of Parentheses","s":"score-of-parentheses","d":"Medium","a":65},
  {"n":862,"t":"Shortest Subarray with Sum at Least K","s":"shortest-subarray-with-sum-at-least-k","d":"Hard","a":25.4},
  {"n":863,"t":"All Nodes Distance K in Binary Tree","s":"all-nodes-distance-k-in-binary-tree","d":"Medium","a":58.6},
  {"n":872,"t":"Leaf-Similar Trees","s":"leaf-similar-trees","d":"Easy","a":64.5},
  {"n":875,"t":"Koko Eating Bananas","s":"koko-eating-bananas","d":"Medium","a":53.7},
  {"n":876,"t":"Middle of the Linked List","s":"middle-of-the-linked-list","d":"Easy","a":69.4},
  {"n":887,"t":"Super Egg Drop","s":"super-egg-drop","d":"Hard","a":27},
  {"n":889,"t":"Construct Binary Tree from Preorder and Postorder Traversal","s":"construct-binary-tree-from-preorder-and-postorder-traversal","d":"Medium","a":68.2},
  {"n":895,"t":"Maximum Frequency Stack","s":"maximum-frequency-stack","d":"Hard","a":63.6},
  {"n":898,"t":"Bitwise ORs of Subarrays","s":"bitwise-ors-of-subarrays","d":"Medium","a":35},
  {"n":901,"t":"Online Stock Span","s":"online-stock-span","d":"Medium","a":61.7},
  {"n":909,"t":"Snakes and Ladders","s":"snakes-and-ladders","d":"Medium","a":39.3},
  {"n":912,"t":"Sort an Array","s":"sort-an-array","d":"Medium","a":63.9},
  {"n":931,"t":"Minimum Falling Path Sum","s":"minimum-falling-path-sum","d":"Medium","a":64.3},
  {"n":937,"t":"Reorder Data in Log Files","s":"reorder-data-in-log-files","d":"Easy","a":55.1},
  {"n":939,"t":"Minimum Area Rectangle","s":"minimum-area-rectangle","d":"Medium","a":52.5},
  {"n":953,"t":"Verifying an Alien Dictionary","s":"verifying-an-alien-dictionary","d":"Easy","a":52.3},
  {"n":957,"t":"Prison Cells After N Days","s":"prison-cells-after-n-days","d":"Medium","a":40.1},
  {"n":970,"t":"Powerful Integers","s":"powerful-integers","d":"Medium","a":43.4},
  {"n":973,"t":"K Closest Points to Origin","s":"k-closest-points-to-origin","d":"Medium","a":64.9},
  {"n":979,"t":"Distribute Coins in Binary Tree","s":"distribute-coins-in-binary-tree","d":"Medium","a":70.1},
  {"n":980,"t":"Unique Paths III","s":"unique-paths-iii","d":"Hard","a":77.1},
  {"n":981,"t":"Time Based Key-Value Store","s":"time-based-key-value-store","d":"Medium","a":54.5},
  {"n":986,"t":"Interval List Intersections","s":"interval-list-intersections","d":"Medium","a":68.8},
  {"n":987,"t":"Vertical Order Traversal of a Binary Tree","s":"vertical-order-traversal-of-a-binary-tree","d":"Hard","a":39.3},
  {"n":992,"t":"Subarrays with K Different Integers","s":"subarrays-with-k-different-integers","d":"Hard","a":51.4},
  {"n":993,"t":"Cousins in Binary Tree","s":"cousins-in-binary-tree","d":"Easy","a":52.4},
  {"n":994,"t":"Rotting Oranges","s":"rotting-oranges","d":"Medium","a":49.8},
  {"n":1000,"t":"Minimum Cost to Merge Stones","s":"minimum-cost-to-merge-stones","d":"Hard","a":40.8},
  {"n":1002,"t":"Find Common Characters","s":"find-common-characters","d":"Easy","a":68.8},
  {"n":1008,"t":"Construct Binary Search Tree from Preorder Traversal","s":"construct-binary-search-tree-from-preorder-traversal","d":"Medium","a":78.9},
  {"n":1010,"t":"Pairs of Songs With Total Durations Divisible by 60","s":"pairs-of-songs-with-total-durations-divisible-by-60","d":"Medium","a":51.1},
  {"n":1011,"t":"Capacity To Ship Packages Within D Days","s":"capacity-to-ship-packages-within-d-days","d":"Medium","a":60.4},
  {"n":1024,"t":"Video Stitching","s":"video-stitching","d":"Medium","a":48.9},
  {"n":1026,"t":"Maximum Difference Between Node and Ancestor","s":"maximum-difference-between-node-and-ancestor","d":"Medium","a":70.1},
  {"n":1031,"t":"Maximum Sum of Two Non-Overlapping Subarrays","s":"maximum-sum-of-two-non-overlapping-subarrays","d":"Medium","a":59},
  {"n":1041,"t":"Robot Bounded In Circle","s":"robot-bounded-in-circle","d":"Medium","a":55},
  {"n":1043,"t":"Partition Array for Maximum Sum","s":"partition-array-for-maximum-sum","d":"Medium","a":68},
  {"n":1044,"t":"Longest Duplicate Substring","s":"longest-duplicate-substring","d":"Hard","a":31.1},
  {"n":1047,"t":"Remove All Adjacent Duplicates In String","s":"remove-all-adjacent-duplicates-in-string","d":"Easy","a":71.6},
  {"n":1057,"t":"Campus Bikes","s":"campus-bikes","d":"Medium","a":58},
  {"n":1060,"t":"Missing Element in Sorted Array","s":"missing-element-in-sorted-array","d":"Medium","a":55.1},
  {"n":1071,"t":"Greatest Common Divisor of Strings","s":"greatest-common-divisor-of-strings","d":"Easy","a":51.9},
  {"n":1087,"t":"Brace Expansion","s":"brace-expansion","d":"Medium","a":63.5},
  {"n":1091,"t":"Shortest Path in Binary Matrix","s":"shortest-path-in-binary-matrix","d":"Medium","a":40.5},
  {"n":1099,"t":"Two Sum Less Than K","s":"two-sum-less-than-k","d":"Easy","a":60.8},
  {"n":1105,"t":"Filling Bookcase Shelves","s":"filling-bookcase-shelves","d":"Medium","a":57.6},
  {"n":1106,"t":"Parsing A Boolean Expression","s":"parsing-a-boolean-expression","d":"Hard","a":59.6},
  {"n":1110,"t":"Delete Nodes And Return Forest","s":"delete-nodes-and-return-forest","d":"Medium","a":68.1},
  {"n":1120,"t":"Maximum Average Subtree","s":"maximum-average-subtree","d":"Medium","a":64.3},
  {"n":1122,"t":"Relative Sort Array","s":"relative-sort-array","d":"Easy","a":68},
  {"n":1135,"t":"Connecting Cities With Minimum Cost","s":"connecting-cities-with-minimum-cost","d":"Medium","a":60},
  {"n":1138,"t":"Alphabet Board Path","s":"alphabet-board-path","d":"Medium","a":51.6},
  {"n":1143,"t":"Longest Common Subsequence","s":"longest-common-subsequence","d":"Medium","a":58.8},
  {"n":1152,"t":"Analyze User Website Visit Pattern","s":"analyze-user-website-visit-pattern","d":"Medium","a":43.2},
  {"n":1155,"t":"Number of Dice Rolls With Target Sum","s":"number-of-dice-rolls-with-target-sum","d":"Medium","a":47.7},
  {"n":1156,"t":"Swap For Longest Repeated Character Substring","s":"swap-for-longest-repeated-character-substring","d":"Medium","a":47.1},
  {"n":1160,"t":"Find Words That Can Be Formed by Characters","s":"find-words-that-can-be-formed-by-characters","d":"Easy","a":67.9},
  {"n":1164,"t":"Product Price at a Given Date","s":"product-price-at-a-given-date","d":"Medium","a":69},
  {"n":1166,"t":"Design File System","s":"design-file-system","d":"Medium","a":58.8},
  {"n":1167,"t":"Minimum Cost to Connect Sticks","s":"minimum-cost-to-connect-sticks","d":"Medium","a":65.3},
  {"n":1169,"t":"Invalid Transactions","s":"invalid-transactions","d":"Medium","a":30.6},
  {"n":1180,"t":"Count Substrings with Only One Distinct Letter","s":"count-substrings-with-only-one-distinct-letter","d":"Easy","a":78.1},
  {"n":1190,"t":"Reverse Substrings Between Each Pair of Parentheses","s":"reverse-substrings-between-each-pair-of-parentheses","d":"Medium","a":64.6},
  {"n":1192,"t":"Critical Connections in a Network","s":"critical-connections-in-a-network","d":"Hard","a":51.6},
  {"n":1197,"t":"Minimum Knight Moves","s":"minimum-knight-moves","d":"Medium","a":38.2},
  {"n":1209,"t":"Remove All Adjacent Duplicates in String II","s":"remove-all-adjacent-duplicates-in-string-ii","d":"Medium","a":57.2},
  {"n":1217,"t":"Minimum Cost to Move Chips to The Same Position","s":"minimum-cost-to-move-chips-to-the-same-position","d":"Easy","a":70.7},
  {"n":1220,"t":"Count Vowels Permutation","s":"count-vowels-permutation","d":"Hard","a":54.1},
  {"n":1222,"t":"Queens That Can Attack the King","s":"queens-that-can-attack-the-king","d":"Medium","a":69.7},
  {"n":1229,"t":"Meeting Scheduler","s":"meeting-scheduler","d":"Medium","a":54.7},
  {"n":1233,"t":"Remove Sub-Folders from the Filesystem","s":"remove-sub-folders-from-the-filesystem","d":"Medium","a":63.1},
  {"n":1235,"t":"Maximum Profit in Job Scheduling","s":"maximum-profit-in-job-scheduling","d":"Hard","a":48.2},
  {"n":1236,"t":"Web Crawler","s":"web-crawler","d":"Medium","a":65},
  {"n":1244,"t":"Design A Leaderboard","s":"design-a-leaderboard","d":"Medium","a":66.9},
  {"n":1249,"t":"Minimum Remove to Make Valid Parentheses","s":"minimum-remove-to-make-valid-parentheses","d":"Medium","a":64.4},
  {"n":1254,"t":"Number of Closed Islands","s":"number-of-closed-islands","d":"Medium","a":62.1},
  {"n":1255,"t":"Maximum Score Words Formed by Letters","s":"maximum-score-words-formed-by-letters","d":"Hard","a":70.4},
  {"n":1268,"t":"Search Suggestions System","s":"search-suggestions-system","d":"Medium","a":65.5},
  {"n":1270,"t":"All People Report to the Given Manager","s":"all-people-report-to-the-given-manager","d":"Medium","a":88.2},
  {"n":1275,"t":"Find Winner on a Tic Tac Toe Game","s":"find-winner-on-a-tic-tac-toe-game","d":"Easy","a":52.9},
  {"n":1277,"t":"Count Square Submatrices with All Ones","s":"count-square-submatrices-with-all-ones","d":"Medium","a":73},
  {"n":1293,"t":"Shortest Path in a Grid with Obstacles Elimination","s":"shortest-path-in-a-grid-with-obstacles-elimination","d":"Hard","a":43.2},
  {"n":1302,"t":"Deepest Leaves Sum","s":"deepest-leaves-sum","d":"Medium","a":85.4},
  {"n":1312,"t":"Minimum Insertion Steps to Make a String Palindrome","s":"minimum-insertion-steps-to-make-a-string-palindrome","d":"Hard","a":60.7},
  {"n":1313,"t":"Decompress Run-Length Encoded List","s":"decompress-run-length-encoded-list","d":"Easy","a":85.5},
  {"n":1314,"t":"Matrix Block Sum","s":"matrix-block-sum","d":"Medium","a":73.9},
  {"n":1328,"t":"Break a Palindrome","s":"break-a-palindrome","d":"Medium","a":48.8},
  {"n":1329,"t":"Sort the Matrix Diagonally","s":"sort-the-matrix-diagonally","d":"Medium","a":81.4},
  {"n":1335,"t":"Minimum Difficulty of a Job Schedule","s":"minimum-difficulty-of-a-job-schedule","d":"Hard","a":56.5},
  {"n":1344,"t":"Angle Between Hands of a Clock","s":"angle-between-hands-of-a-clock","d":"Medium","a":61.4},
  {"n":1345,"t":"Jump Game IV","s":"jump-game-iv","d":"Hard","a":42.2},
  {"n":1351,"t":"Count Negative Numbers in a Sorted Matrix","s":"count-negative-numbers-in-a-sorted-matrix","d":"Easy","a":75.7},
  {"n":1360,"t":"Number of Days Between Two Dates","s":"number-of-days-between-two-dates","d":"Easy","a":46.5},
  {"n":1365,"t":"How Many Numbers Are Smaller Than the Current Number","s":"how-many-numbers-are-smaller-than-the-current-number","d":"Easy","a":86},
  {"n":1376,"t":"Time Needed to Inform All Employees","s":"time-needed-to-inform-all-employees","d":"Medium","a":57.1},
  {"n":1382,"t":"Balance a Binary Search Tree","s":"balance-a-binary-search-tree","d":"Medium","a":76.8},
  {"n":1386,"t":"Cinema Seat Allocation","s":"cinema-seat-allocation","d":"Medium","a":36.8},
  {"n":1395,"t":"Count Number of Teams","s":"count-number-of-teams","d":"Medium","a":73},
  {"n":1405,"t":"Longest Happy String","s":"longest-happy-string","d":"Medium","a":53.1},
  {"n":1429,"t":"First Unique Number","s":"first-unique-number","d":"Medium","a":50.3},
  {"n":1431,"t":"Kids With the Greatest Number of Candies","s":"kids-with-the-greatest-number-of-candies","d":"Easy","a":88},
  {"n":1448,"t":"Count Good Nodes in Binary Tree","s":"count-good-nodes-in-binary-tree","d":"Medium","a":72.1},
  {"n":1465,"t":"Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts","s":"maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts","d":"Medium","a":36.9},
  {"n":1479,"t":"Sales by Day of the Week","s":"sales-by-day-of-the-week","d":"Hard","a":83.1},
  {"n":1480,"t":"Running Sum of 1d Array","s":"running-sum-of-1d-array","d":"Easy","a":88.9},
  {"n":1481,"t":"Least Number of Unique Integers after K Removals","s":"least-number-of-unique-integers-after-k-removals","d":"Medium","a":56.1},
  {"n":1483,"t":"Kth Ancestor of a Tree Node","s":"kth-ancestor-of-a-tree-node","d":"Hard","a":32.8},
  {"n":1487,"t":"Making File Names Unique","s":"making-file-names-unique","d":"Medium","a":31.8},
  {"n":1491,"t":"Average Salary Excluding the Minimum and Maximum Salary","s":"average-salary-excluding-the-minimum-and-maximum-salary","d":"Easy","a":68},
  {"n":1496,"t":"Path Crossing","s":"path-crossing","d":"Easy","a":55.2},
  {"n":1511,"t":"Customer Order Frequency","s":"customer-order-frequency","d":"Easy","a":74.6},
  {"n":1539,"t":"Kth Missing Positive Number","s":"kth-missing-positive-number","d":"Easy","a":54.7},
  {"n":1547,"t":"Minimum Cost to Cut a Stick","s":"minimum-cost-to-cut-a-stick","d":"Hard","a":53.2},
  {"n":1559,"t":"Detect Cycles in 2D Grid","s":"detect-cycles-in-2d-grid","d":"Hard","a":45},
  {"n":1596,"t":"The Most Frequently Ordered Products for Each Customer","s":"the-most-frequently-ordered-products-for-each-customer","d":"Medium","a":85.3},
  {"n":1597,"t":"Build Binary Expression Tree From Infix Expression","s":"build-binary-expression-tree-from-infix-expression","d":"Hard","a":59},
  {"n":1600,"t":"Throne Inheritance","s":"throne-inheritance","d":"Medium","a":61.3},
  {"n":1603,"t":"Design Parking System","s":"design-parking-system","d":"Easy","a":86.5},
  {"n":1628,"t":"Design an Expression Tree With Evaluate Function","s":"design-an-expression-tree-with-evaluate-function","d":"Medium","a":80.7},
  {"n":1629,"t":"Slowest Key","s":"slowest-key","d":"Easy","a":59},
  {"n":1636,"t":"Sort Array by Increasing Frequency","s":"sort-array-by-increasing-frequency","d":"Easy","a":67.2},
  {"n":1641,"t":"Count Sorted Vowel Strings","s":"count-sorted-vowel-strings","d":"Medium","a":75.1},
  {"n":1647,"t":"Minimum Deletions to Make Character Frequencies Unique","s":"minimum-deletions-to-make-character-frequencies-unique","d":"Medium","a":55.6},
  {"n":1648,"t":"Sell Diminishing-Valued Colored Balls","s":"sell-diminishing-valued-colored-balls","d":"Medium","a":31},
  {"n":1650,"t":"Lowest Common Ancestor of a Binary Tree III","s":"lowest-common-ancestor-of-a-binary-tree-iii","d":"Medium","a":76.7},
  {"n":1670,"t":"Design Front Middle Back Queue","s":"design-front-middle-back-queue","d":"Medium","a":54.3},
  {"n":1673,"t":"Find the Most Competitive Subsequence","s":"find-the-most-competitive-subsequence","d":"Medium","a":45.8},
  {"n":1710,"t":"Maximum Units on a Truck","s":"maximum-units-on-a-truck","d":"Easy","a":70.1},
  {"n":1730,"t":"Shortest Path to Get Food","s":"shortest-path-to-get-food","d":"Medium","a":55.4},
  {"n":1740,"t":"Find Distance in a Binary Tree","s":"find-distance-in-a-binary-tree","d":"Medium","a":68.8},
  {"n":1751,"t":"Maximum Number of Events That Can Be Attended II","s":"maximum-number-of-events-that-can-be-attended-ii","d":"Hard","a":48.8},
  {"n":1761,"t":"Minimum Degree of a Connected Trio in a Graph","s":"minimum-degree-of-a-connected-trio-in-a-graph","d":"Hard","a":38.3},
  {"n":1770,"t":"Maximum Score from Performing Multiplication Operations","s":"maximum-score-from-performing-multiplication-operations","d":"Medium","a":30.3},
  {"n":1783,"t":"Grand Slam Titles","s":"grand-slam-titles","d":"Medium","a":90.3},
  {"n":1799,"t":"Maximize Score After N Operations","s":"maximize-score-after-n-operations","d":"Hard","a":44.6},
  {"n":1869,"t":"Longer Contiguous Segments of Ones than Zeros","s":"longer-contiguous-segments-of-ones-than-zeros","d":"Easy","a":59.7}
];
